controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    # velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
effort_controller:
  ros__parameters:
    joints:
      - gripper

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

# velocity_controller:
#   ros__parameters:
#     joints:
#       - gripper

# position_controller:
#   ros__parameters:
#     joints:
#       - gripper

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - gripper
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity